source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'devise', '1.4.2'
gem 'braintree'
gem 'rack', '1.3.0'

group :development, :test do
  gem 'rspec', '2.6.0'
  gem 'rspec-rails', '2.6.1'
  gem 'capybara', "1.0.0.beta1"
  gem 'launchy'
end
