source 'http://rubygems.org'

gem 'rails', '3.0.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'devise', '1.4.2'
gem 'braintree'

group :development, :test do
  gem 'rspec', '2.0.0'
  gem 'rspec-rails', '2.0.0'
  gem 'capybara'
end
